# Как часто плагин должен сохранять всех миньонов?
# Плагин сохраняет изменения в реальном времени, это только для обновления статистики миньонов в базе данных.
# Чтобы это изменение вступило в силу, необходимо перезапустить сервер!
auto-save-minutes: 3

# Как далеко может находиться сундук-хранилище от миньона
max-linking-distance: 30

# Нужно ли игрокам иметь разрешение 'axminions.place.<миньон>'
# чтобы иметь возможность разместить этого миньона
place-permissions: false

# Стандартное количество миньонов, которое может иметь игрок.
# Это значение может быть переопределено разрешением 'axminions.limit.<количество>'!
default-minion-limit: 5

# Если true, только владелец этого миньона может сломать его
# Если false, каждый, кто может ломать блоки в этом месте, может сломать миньона
# Вам следует включить это, если вы не используете поддерживаемый плагин защиты!
only-owner-break: true

# Если true, только владелец этого миньона может открывать его GUI
# Если false, каждый, кто может ломать блоки в этом месте, может открыть GUI этого миньона
# Вам следует включить это, если вы не используете поддерживаемый плагин защиты!
only-owner-gui: true

# Должны ли миньоны показывать голограммы при возникновении проблемы?
# (Они не будут жаловаться на отсутствие девушки!)
# Вы можете настроить эти сообщения в messages.yml
display-warnings: true

# Если установлено в true, миньон не сломает инструмент, он останется с 1 прочностью (и миньон остановится)
# Если установлено в false, миньон может сломать инструмент
can-break-tools: true

# Лимит миньонов для использования на островах
island-limit: 10

# Должен ли миньон тратить прочность своего инструмента
use-durability: true

# Должен ли миньон доставать новые инструменты из сундука, к которому он подключён
pull-tools-from-chest: false

# Должен ли миньон работать, когда владелец не в сети (только если чанк загружен)
work-when-owner-offline: true

# Максимальное количество блоков, которое один миньон-лесоруб может сломать за один тик
max-breaks-per-tick: 200

# Какой тип сообщения отправлять при неудачном улучшении
# из-за недостаточных средств
# Возможные варианты: chat, title, subtitle, actionbar
upgrade-fail: chat

# Звук, который проигрывается при улучшении миньона
# Установите "" чтобы отключить!
# Список звуков: https://jd.papermc.io/paper/1.20/org/bukkit/Sound.html
upgrade-sound: ENTITY_PLAYER_LEVELUP

database:
  # Может быть H2 (поддержка SqLite планируется)
  type: H2

hooks:
  # Поддерживаемые плагины стакеров: WildStacker, RoseStacker, none
  stacker: none
  # Поддерживаемые провайдеры экономики: Vault, PlayerPoints, custom
  economy: Vault
  # Поддерживаемые провайдеры цен: ShopGUIPlus, Essentials, EconomyShopGUI, CMI, custom
  prices: EconomyShopGUI

charge:
  enabled: false
  amount: 1800 # в секундах
  max-charge: 1440 # в минутах
  price: 10000
  minimum-charge: 30 # в секундах
  items:
    '1':
      type: coal
      name: <red>Топливо
      charge: 1000 # В секундах

# 1 - ЧЧ:ММ:СС, например 01:25:35
# 2 - короткий формат, например 20м
# 3 - текстовый формат, например 01ч 25м 35с
timer-format: 1

gui:
  size: 27
  items:
    filler:
      type: black_stained_glass_pane
      name: ''
    rotate:
      type: ender_eye
      name: <#33FF33><b>Повернуть
      lore:
      - ''
      - ' <gray>- <white>Сейчас: <#33FF33><direction>'
      - ''
      - <#33FF33><b>(!)</b> Нажмите здесь, чтобы повернуть миньона!
      slot: 10
    link:
      type: chest
      name: <#FFCC00><b>Привязать к контейнеру
      lore:
      - ''
      - ' <gray>- <white>Статус: <#FFCC00><linked>'
      - ''
      - <#FFCC00><b>(!)</b> Нажмите здесь, чтобы привязать миньона к контейнеру!
      slot: 11
    item:
      type: air
      slot: 13
    charge:
      type: lava_bucket
      name: <#FB8E08><b>Зарядить
      lore:
      - ''
      - ' <gray>- <white>Текущий заряд: <#FFCC00><charge>'
      - ''
      - <#FB8E08><b>(!)</b> Нажмите здесь, чтобы зарядить миньона на <white>30 минут</white>!
      slot: 9

    # Эти настройки специфичны для каждого миньона, вы можете редактировать их в файле каждого миньона!
    upgrade:
      slot: 15
    bonus-loot-upgrade:
      slot: 14
    statistics:
      slot: 16
# Изменяйте это, только если вас попросили! Это ухудшит производительность и будет спамить сообщениями в консоль!
# Требуется перезапуск!
debug: false

# Не изменяйте!
config-version: 11
